version: "3.9"
services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "5000:5000"
  test:
    depends_on:
      - web
    build:
      dockerfile: docker/Dockerfile_test
      context: .
    environment:
      - SERVER_HOST=web
